name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # define a cache
      - name: Cache buildozer
        id: cache-buildozer
        uses: actions/cache@v3
        env:
          cache-name: cache-buildozer-and-brainbay
        with:
          path: |
            .buildozer_global
            .buildozer
            brainflow
            .venv
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-buildozer.outputs.cache-hit != 'true' }}
        name: create virtual env
        continue-on-error: true
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          echo "currennt dir:"
          pwd
          ls -lA
          # pip install -r requirements.txt

        # - name: Set up Python
        #   uses: actions/setup-python@v3
        #   with:
        #     python-version: 3.9
        #     cache: pip, brainflow, kivy, kivy-Garden, kivy-examples, kiwisolver, ffpyplayer, matplotlib, ninja, numpy, cmake, pandas, cffi

      # see if cache was found and run a check command
      - if: ${{ steps.cache-buildozer.outputs.cache-hit == 'true' }}
        name: List contents of cache
        continue-on-error: true
        run: |
          source ./.venv/bin/activate
          echo "----(venv) pip list---"
          pip list
          echo "----content of .buildozer---"
          ls .buildozer
          echo "----content of brainbay----"
          ls brainflow

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "kivy[base,media]" kivy_examples
          python -m pip install matplotlib ninja numpy cmake

      - name: Check Kivy and brainflow version
        continue-on-error: true
        run: |
          python -c "import kivy; print(f'Kivy version: {kivy.__version__}')"
          echo "see if brainflow is still here"
          ls -Al
          echo "check if brainflow and kiwy can be found by 'pip show'"
          pip show brainflow kivy kivy-garden

          #  # if dir brainflow exists, this will just throw an error and give up
          #  - name: Clone brainflow repository
          #    continue-on-error: true
          #    uses: actions/checkout@v3
          #    with:
          #      repository: brainflow-dev/brainflow
          #      ref: master # specify the branch or commit you want to clone
          #      path: brainflow # specify the destination directory where you want to clone

      - name: Compile brainflow
        run: |
          if ! pip show brainflow; then
            # download the sourcefiles
            if [ ! -d "brainflow" ]; then
              git clone --single-branch --branch master https://github.com/brainflow-dev/brainflow.git
            else
              echo "repository downloaded found in cache. go straight to comipling.. "
            fi
            echo "brainflow package not yet installed. compiling and installing..."
            cd brainflow
            rm build/* -rf
            cd tools
            python build.py
            cd ../python_package
            python -m pip install -U .
            cd ../..
          else
            echo "brainflow package already installed. skip compiling."
          fi
          # if [ -f "build/libBrainflow.a" ] && \
          #    [ -f "build/libDSPFilters.a" ] && \
          #    [ -f "build/libWaveLib.a" ] && \
          #    [ -f "build/libkissfft-double.a" ]; then
          #   # Run your command here
          #   echo "All files exist, no need to comiple"
          # else
          #   echo "One or more files are missing, removing build dir and run build.py"
          # fi

      - name: Check Brainflow version
        continue-on-error: true
        run: |
          python -c "from brainflow.board_shim import BoardShim; print( 'Brainflow version: ' + BoardShim.get_version() )"
          pip show brainflow kiwy kivy-garden

      #---compile with buildozer

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v2
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
