name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install kivy
          python -m pip install matplotlib ninja numpy cmake

      - name: Check Kivy version
        run: |
          python -c "import kivy; print(f'Kivy version: {kivy.__version__}')"
          echo "see if brainflow is still here"
          ls -l

      - name: Clone brainflow repository
        uses: actions/checkout@v3
        with:
          repository: brainflow-dev/brainflow
          ref: master # specify the branch or commit you want to clone
          path: brainflow # specify the destination directory where you want to clone

      - name: Compile brainflow
        run: |
          cd brainflow
          cd tools
          python build.py
          cd ../python_package
          python -m pip install -U .

      - name: Check Brainflow version
        run: |
          python -c "from brainflow.board_shim import BoardShim; print( 'Brainflow version: ' + BoardShim.get_version() )"

      #---compile with buildozer

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_ENV
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
